baseURL = 'https://opheliagame.github.io/blo-sir-take-action/'
languageCode = 'en-us'
title = 'Take Action to Reduce Work Pressure on BLOs During SIR'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

theme = ["mainroad"]

[params.reveal_hugo]
theme = "solarized"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true