baseURL = "/"
languageCode = 'en-us'
title = 'Take Action to Reduce Work Pressure on BLOs During SIR'

theme = ["mainroad", "reveal-hugo"]

[params.reveal_hugo]
theme = "solarized"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true